### Global Build Settings
safe: true
lsi: false

markdown: kramdown
url: "http://leomeloxp.github.io"


## Global Settings
email: leomeloxp@gmail.com
twitter_username: leomeloxp
github_username:  leomeloxp


## Individual Website Settings
title: Leo's Github Projects
description: > # this means to ignore newlines until "baseurl:"
  This is a base website where I might share some of my projects as subpages.
  The main purpose of this website is to actually improve my Rails skills and teach myself some jekyll.
baseurl: "" # the subpath of your site

name: gh-pages
project: gh-pages
main_site_url: http://leomeloxp.github.io
projects_site_url: http://leomeloxp.github.io/projects
# Project github URL
github_repo_url: https://github.com/leomeloxp/gh-pages